# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.

variable "account_file" {
  type    = string
  default = "./credentials.json"
}

variable "app_env" {
  type    = string
  default = env("APP_ENV")
}

variable "version" {
  type    = string
  default = env("VERSION")
}

variable "consul_http_addr" {
  type    = string
  default = env("CONSUL_HTTP_ADDR")
}

variable "consul_http_token" {
  type    = string
  default = env("CONSUL_HTTP_TOKEN")
}
# https://www.packer.io/docs/templates/hcl_templates/functions/contextual/consul
locals {
  project_id = consul_key(join("/", ["polymathes/temporal", var.app_env, "packer/project-id"]))
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
# https://www.packer.io/plugins/builders/azure/arm
source "googlecompute" "basic-example" {
  account_file = var.account_file
  project_id   = local.project_id
  image_name   = "bastion"
  machine_type = "e2-medium"
  source_image = "ubuntu-2204-jammy-v20220810"
  ssh_username = "ubuntu"
  zone         = "southamerica-west1-a"
}

build {
  hcp_packer_registry {
    bucket_name = "gcp"
    description = <<EOT
Some nice description about the image being published to HCP Packer Registry.
    EOT
    bucket_labels = {
      "Owner"          = "jveraduran"
      "OS"             = "Ubuntu",
      "Ubuntu-version" = "22.04 LTS",
      "Environment"    = var.app_env
    }

    build_labels = {
      "build-time"   = timestamp()
      "build-source" = basename(path.cwd)
    }
  }
  sources = [
    "sources.googlecompute.basic-example"
  ]
}




